feat(format): add `base` and `defaults`
ember-intl/ember-intl pull request #1463
Opened 2020-11-05 22:21 UTC by buschtoens

Closes #1462.

2020-11-06 09:31 UTC, buschtoens commented
@jasonmit What do you think about this API? Too over-engineered? Should we drop either `base` or `defaults`? Or do you like it?

2020-11-07 02:04 UTC, jasonmit commented
I can't immediately tell the difference between base and defaults - likely will be confusing for users as well.  I think we should drop one in favor of simplifying the API.

More important, all the formats into `intl-messageformat` since they're used within the translation syntax.  I don't believe `intl-messageformat` would have knowledge of base | default.

I'd expect these two to yield the same results when there's a base/default set:
`{{format-time timestamp}}`
`{{format-message '{timestamp, time}'}}`

If that's already the case (I don't know as I didn't look into the implementation too closely) then just write some tests so that we don't break that behavior in the future.

2020-11-14 23:41 UTC, jasonmit requested changes
I love the overall feature but struggled to understand the difference between base and defaults - likely will be confusing for users.  I think we should drop one in favor of simplifying the API (maybe `base`?).

We should also make sure/write a test for supporting using the default key from within a translation string:
`"The time is {timestamp, time, default}"`

I believe we pass the whole formats object to `intl-messageformat` but since `default` is top-level instead of under the individual format options objects (time, date, relative, number) you may need to do a bit of work to achieve that.  To keep things simple, we can move defaults under `time`, `date`, , etc. and release a new major.

2021-03-15 16:21 UTC, elonmulder commented
@buschtoens @jasonmit Are there any plans on moving forward with this PR?

2023-07-01 12:53 UTC, ijlee2 commented
Will close the issue, as the underlying assumptions might have changed since November 2020.

2023-07-01 12:53 UTC, closed without merging